# Generated by Django 4.2 on 2023-04-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbank_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('small_talk', 'Small Talk'), ('technical', 'Technical'), ('behavioral', 'Behavioral')], max_length=20)),
                ('hashtags', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='promptword',
            name='category',
        ),
        migrations.DeleteModel(
            name='PromptCategory',
        ),
        migrations.DeleteModel(
            name='PromptWord',
        ),
    ]
