# Generated by Django 4.2 on 2023-04-21 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview_tool', '0003_remove_response_prompt'),
        ('wordbank_manager', '0002_prompt_remove_promptword_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StandardPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('small_talk', 'Small Talk'), ('technical', 'Technical'), ('behavioral', 'Behavioral')], max_length=20)),
                ('hashtags', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('hashtags', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ManyToManyField(blank=True, to='wordbank_manager.promptcategory')),
            ],
        ),
        migrations.DeleteModel(
            name='Prompt',
        ),
    ]
