# Generated by Django 4.2 on 2023-04-25 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wordbank_manager', '0003_promptcategory_standardprompt_userprompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprompt',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='standardprompt',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprompt',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
