# Generated by Django 4.2 on 2023-04-21 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordbank_manager', '0002_prompt_remove_promptword_category_and_more'),
        ('interview_tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_tool.interview')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordbank_manager.prompt')),
            ],
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='interview',
        ),
        migrations.DeleteModel(
            name='PromptLog',
        ),
        migrations.DeleteModel(
            name='PromptWord',
        ),
        migrations.DeleteModel(
            name='Transcript',
        ),
    ]
