# Generated by Django 4.2 on 2023-04-21 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview_tool', '0002_response_remove_transcript_interview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='prompt',
        ),
    ]
